#NumPy

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# 0 dimension
import numpy as np
arr = np.array([42,34])
print(arr)

[42 34]


In [ ]:
# 1 dimension
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# 2 dimension
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# High dimension
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=6)
print(arr)

[[[[[[1 2 3 4]]]]]]


In [ ]:
# Check dimension
import numpy as np
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)

3


In [ ]:
# Array indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,3])
print(arr[0,-2])

9
4


In [ ]:
# Array slicing 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
#Data type check
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [ ]:
# Array shape
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
# Reshape array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Matrix operation
import numpy as np
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print ("Addition of two matrices: ")
print (np.add(x,y))

print ("Subtraction of two matrices : ")
print (np.subtract(x,y))

print ("Matrix Division : ")
print (np.divide(x,y))

print ("Multiplication of two matrices: ")
print (np.multiply(x,y))

print ("The product of two matrices : ")
print (np.dot(x,y))

print ("square root is : ")
print (np.sqrt(x))
print ("The summation of elements : ")
print (np.sum(y))

print ("The column wise summation  : ")
print (np.sum(y,axis=0))

print ("The row wise summation: ")
print (np.sum(y,axis=1))

print ("Matrix transposition : ")
print (x.T)

Addition of two matrices: 
[[ 8 10]
 [13 15]]
Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]
Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
Multiplication of two matrices: 
[[ 7 16]
 [36 50]]
The product of two matrices : 
[[25 28]
 [73 82]]
square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of elements : 
34
The column wise summation  : 
[16 18]
The row wise summation: 
[15 19]
Matrix transposition : 
[[1 4]
 [2 5]]


#Pandas

In [ ]:
# Dataframe creat
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford","A"],
  'passings': [3, 7, 2,6],
  'year':[1990,1820,2013,2020]
}

df = pd.DataFrame(mydataset)
print(df)

    cars  passings  year
0    BMW         3  1990
1  Volvo         7  1820
2   Ford         2  2013
3      A         6  2020


In [ ]:
#refer to the row index:
print(df.loc[1])

cars        Volvo
passings        7
year         1820
Name: 1, dtype: object


In [ ]:
df.shape

(4, 3)

In [ ]:
#use a list of indexes:
print(df.loc[[0, 1]])

    cars  passings  year
0    BMW         3  1990
1  Volvo         7  1820


In [ ]:
print(df.cars)

0      BMW
1    Volvo
2     Ford
3        A
Name: cars, dtype: object


In [ ]:
print(df.passings)

0    3
1    7
2    2
Name: passings, dtype: int64
